name: start
on: [push]
jobs:
    generate_html:
        runs-on: ubuntu-20.04
        container: 
            image: jonasknebel/resolver_for_yaml_dependencies:latest     
        steps:
        - uses: actions/checkout@master
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo   
        - name: Create local changes
          run: for filename in ./*.yaml; do redoc-cli bundle -o ./docs/${filename:2:$((${#filename})) - 7}.html $filename; done        
        - name: Add Files
          run: git add docs/*
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "Add changes" -a --allow-empty
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}     
 
        - name: Checkout
          uses: actions/checkout@master # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
          with:
            persist-credentials: false
        - name: Install rsync ðŸ“š
          run: |
            npm i rsync
        - name: Deploy ðŸš€
          uses: JamesIves/github-pages-deploy-action@3.6.2
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: master
            BRANCH: gh-pages  # The branch the action should deploy to.
            FOLDER: docs # The folder the action should deploy.
            CLEAN: true # Automatically remove deleted files from the deploy branch
           

          
         